"""day13c task_assignments + annotation review

Revision ID: 0f97ec83e942
Revises: 72c05f0bee37
Create Date: 2026-09-25 14:40:18.562256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f97ec83e942'
down_revision: Union[str, None] = '72c05f0bee37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('reviewed_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('review_comment', sa.String(length=1000), nullable=True))
        batch_op.create_index(batch_op.f('ix_annotations_review_status'), ['review_status'], unique=False)
        batch_op.create_foreign_key('fk_annotations_reviewed_by_users', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_annotations_reviewed_by_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_annotations_review_status'))
        batch_op.drop_column('review_comment')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
