"""task_assignments

Revision ID: 19dccf139dd7
Revises: 22699153119f
Create Date: 2026-09-27 15:27:38.676810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dccf139dd7'
down_revision: Union[str, None] = '22699153119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', 'role', name='uq_task_user_role')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignments_user_id'), ['user_id'], unique=False)

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_task_id'))

    op.drop_table('task_assignments')
    # ### end Alembic commands ###
