"""day18 annotation_comments

Revision ID: 5a16db5c1d95
Revises: f055bef71bde
Create Date: 2026-09-30 16:30:05.393918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a16db5c1d95'
down_revision: Union[str, None] = 'f055bef71bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('annotation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_comments_annotation_id'), ['annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_comments_created_at'), ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_annotation_comments_annotation_id'))

    op.drop_table('annotation_comments')
    # ### end Alembic commands ###

