"""day14 video_assets + annotation tracks

Revision ID: 6f185d8f3a2f
Revises: 7dcc80520060
Create Date: 2026-09-25 17:30:56.513515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f185d8f3a2f'
down_revision: Union[str, None] = '7dcc80520060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('frames_dir', sa.String(length=1000), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_error', sa.String(length=1000), nullable=True),
    sa.Column('extraction_job_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_assets_extraction_status'), ['extraction_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_assets_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('is_keyframe', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('outside', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_annotations_track_id'), ['track_id'], unique=False)

    op.create_index(
        "ix_annotations_track_frame",
        "annotations",
        ["track_id", "frame"],
        postgresql_where=sa.text("track_id IS NOT NULL"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_annotations_track_frame", table_name="annotations")
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_track_id'))
        batch_op.drop_column('outside')
        batch_op.drop_column('is_keyframe')
        batch_op.drop_column('track_id')

    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_assets_task_id'))
        batch_op.drop_index(batch_op.f('ix_video_assets_extraction_status'))

    op.drop_table('video_assets')
    # ### end Alembic commands ###

