"""day26 tool_configs user_preferences

Revision ID: 77f60d245d76
Revises: 31198146b459
Create Date: 2026-10-05 14:45:45.202227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '77f60d245d76'
down_revision: Union[str, None] = '31198146b459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index('ix_tool_configs_project_id')
        batch_op.drop_index('ix_tool_configs_task_id')
        batch_op.drop_constraint('uq_tool_config_project_task', type_='unique')
        batch_op.create_index(batch_op.f('ix_tool_configs_org_id'), ['org_id'], unique=True)
        batch_op.create_foreign_key('fk_org_id', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('auto_open_label_picker')
        batch_op.drop_column('created_at')
        batch_op.drop_column('project_id')
        batch_op.drop_column('task_id')
        batch_op.drop_column('undo_history_depth')
        batch_op.drop_column('show_minimap')
        batch_op.drop_column('autosave_debounce_ms')
        batch_op.drop_column('snap_to_edge')
        batch_op.drop_column('enabled_groups')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('overrides',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_index('ix_user_preferences_project_id')
        batch_op.drop_constraint('uq_user_prefs_project', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_preferences_org_id'), ['org_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_prefs_org', ['user_id', 'org_id'])
        batch_op.create_foreign_key('fk_org_id', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.BIGINT(), nullable=False))
        batch_op.create_foreign_key('fk_old_project', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_prefs_org', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_preferences_org_id'))
        batch_op.create_unique_constraint('uq_user_prefs_project', ['user_id', 'project_id'])
        batch_op.create_index('ix_user_preferences_project_id', ['project_id'], unique=False)
        batch_op.alter_column('overrides',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('org_id')

    with op.batch_alter_table('tool_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_groups', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('snap_to_edge', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('autosave_debounce_ms', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('show_minimap', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('undo_history_depth', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('auto_open_label_picker', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key('fk_old_project', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_old_task', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_tool_configs_org_id'))
        batch_op.create_unique_constraint('uq_tool_config_project_task', ['project_id', 'task_id'])
        batch_op.create_index('ix_tool_configs_task_id', ['task_id'], unique=False)
        batch_op.create_index('ix_tool_configs_project_id', ['project_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('org_id')
    # ### end Alembic commands ###
