"""day25 image_annotation_status

Revision ID: 7eea462f0347
Revises: eaccedd17076
Create Date: 2026-10-01 15:28:25.429452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eea462f0347'
down_revision: Union[str, None] = 'eaccedd17076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_annotation_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'image_id', 'user_id', name='uq_image_status_user')
    )
    with op.batch_alter_table('image_annotation_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_annotation_status_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_annotation_status_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_annotation_status_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_annotation_status_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_notifications_user_unread'))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_active'))

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_task_assignments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_task_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_active'), ['user_id', 'expires_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_unread'), ['user_id', 'created_at'], unique=False)
        batch_op.alter_column('resource_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('image_annotation_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_annotation_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_image_annotation_status_task_id'))
        batch_op.drop_index(batch_op.f('ix_image_annotation_status_status'))
        batch_op.drop_index(batch_op.f('ix_image_annotation_status_image_id'))

    op.drop_table('image_annotation_status')
    # ### end Alembic commands ###
