"""day17 label attributes + mask annotations

Revision ID: 90d8c35c24fd
Revises: ec9df8546ce1
Create Date: 2026-09-27 16:33:56.879639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d8c35c24fd'
down_revision: Union[str, None] = 'ec9df8546ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attributes', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('attributes')

    # ### end Alembic commands ###
