"""day27 tool_configs project scoping

Revision ID: ac599e8d1618
Revises: 77f60d245d76
Create Date: 2026-10-05 15:26:19.062809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac599e8d1618'
down_revision: Union[str, None] = '77f60d245d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.BigInteger(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tool_configs_org_id'))
        batch_op.create_index(batch_op.f('ix_tool_configs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_configs_project_id'), ['project_id'], unique=False)
        batch_op.create_unique_constraint('uq_tool_config_org_project', ['org_id', 'project_id'])
        batch_op.create_foreign_key('fk_tool_configs_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_configs', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_tool_config_org_project', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tool_configs_project_id'))
        batch_op.drop_index(batch_op.f('ix_tool_configs_org_id'))
        batch_op.create_index(batch_op.f('ix_tool_configs_org_id'), ['org_id'], unique=1)
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
