"""day 20 notification

Revision ID: ba7092c52793
Revises: 90d8c35c24fd
Create Date: 2026-09-28 18:58:06.064171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7092c52793'
down_revision: Union[str, None] = '90d8c35c24fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('annotations', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_foreign_key('fk_annotations_created_by_users', 'users', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tasks', schema=None, naming_convention=naming_convention) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_tasks_project_id_projects', type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_project_id_projects_cascade', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('tasks', schema=None, naming_convention=naming_convention) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_tasks_project_id_projects_cascade', type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_project_id_projects', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('annotations', schema=None, naming_convention=naming_convention) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_annotations_created_by_users', type_='foreignkey')

    # ### end Alembic commands ###
