"""day7 label usage + image assets index

Revision ID: c3c7b35a0fbb
Revises: 3bd604aa2f80
Create Date: 2026-09-23 16:03:47.069219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c7b35a0fbb'
down_revision: Union[str, None] = '3bd604aa2f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

