"""day20 task last_submitted_at

Revision ID: e7091f0765e1
Revises: ba7092c52793
Create Date: 2026-09-28 20:29:23.322891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7091f0765e1'
down_revision: Union[str, None] = 'ba7092c52793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('tasks', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('last_submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_submitted_by', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_last_submitted_by_users', 'users', ['last_submitted_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('tasks', schema=None, naming_convention=naming_convention) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_tasks_last_submitted_by_users', type_='foreignkey')
        batch_op.drop_column('last_submitted_by')
        batch_op.drop_column('last_submitted_at')

    # ### end Alembic commands ###
