"""day16 export_import_jobs

Revision ID: ec9df8546ce1
Revises: 19dccf139dd7
Create Date: 2026-09-27 16:19:54.227667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9df8546ce1'
down_revision: Union[str, None] = '19dccf139dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('include_images', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_task_id'), ['task_id'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('label_mapping', sa.Text(), nullable=True),
    sa.Column('as_preannotations', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_task_id'), ['task_id'], unique=False)

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_created_at'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_created_at'))

    op.drop_table('export_jobs')
    # ### end Alembic commands ###
